In [4]:
import pandas as pd
from Bio.KEGG.KGML.KGML_parser import read

In [3]:
pathway = read(open("hsa00010.xml", 'r'))
print(pathway)

Pathway: Glycolysis / Gluconeogenesis
KEGG ID: path:hsa00010
Image file: https://www.kegg.jp/kegg/pathway/hsa/hsa00010.png
Organism: hsa
Entries: 101
Entry types:
	ortholog: 29
	gene: 34
	compound: 31
	map: 7

In [10]:
entries_data = []
for entry in pathway.entries.values():
    entries_data.append({
        'id': entry.id,
        'name': entry.name,
        'type': entry.type,
        'link': entry.link,
        'reaction': entry.reaction,
    })
entries_df = pd.DataFrame(entries_data)
entries_df

,id,name,type,link,reaction
0,18,hsa:226 hsa:229 hsa:230,gene,https://www.kegg.jp/dbget-bin/www_bget?hsa:226...,rn:R01068
1,42,hsa:217 hsa:219 hsa:223 hsa:224 hsa:501,gene,https://www.kegg.jp/dbget-bin/www_bget?hsa:217...,rn:R00710
2,43,ko:K01905 ko:K22224 ko:K24012,ortholog,https://www.kegg.jp/dbget-bin/www_bget?K01905+...,rn:R00229
3,44,hsa:218 hsa:221 hsa:222,gene,https://www.kegg.jp/dbget-bin/www_bget?hsa:218...,rn:R00711
4,45,cpd:C00033,compound,https://www.kegg.jp/dbget-bin/www_bget?C00033,
...,...,...,...,...,...
96,154,ko:K00174 ko:K00175,ortholog,https://www.kegg.jp/dbget-bin/www_bget?K00174+...,rn:R01196
97,156,ko:K00895 ko:K21071,ortholog,https://www.kegg.jp/dbget-bin/www_bget?K00895+...,rn:R00764
98,157,ko:K22473 ko:K22474,ortholog,https://www.kegg.jp/dbget-bin/www_bget?K22473+...,rn:R09479
99,158,ko:K01006,ortholog,https://www.kegg.jp/dbget-bin/www_bget?K01006,rn:R00206
100,159,ko:K01007,ortholog,https://www.kegg.jp/dbget-bin/www_bget?K01007,rn:R00199

In [14]:
human_genes_df = entries_df[entries_df['type'] == 'gene'] 
human_genes_df.head()

,id,name,type,link,reaction
0,18,hsa:226 hsa:229 hsa:230,gene,https://www.kegg.jp/dbget-bin/www_bget?hsa:226...,rn:R01068
1,42,hsa:217 hsa:219 hsa:223 hsa:224 hsa:501,gene,https://www.kegg.jp/dbget-bin/www_bget?hsa:217...,rn:R00710
3,44,hsa:218 hsa:221 hsa:222,gene,https://www.kegg.jp/dbget-bin/www_bget?hsa:218...,rn:R00711
8,49,hsa:10327,gene,https://www.kegg.jp/dbget-bin/www_bget?hsa:10327,rn:R00746
9,50,hsa:124 hsa:125 hsa:126 hsa:127 hsa:128 hsa:13...,gene,https://www.kegg.jp/dbget-bin/www_bget?hsa:124...,rn:R00754

In [18]:
for idx, row in human_genes_df.iterrows():
    gene_names = row['name'].split(' ')
    print(gene_names)

['hsa:226', 'hsa:229', 'hsa:230']
['hsa:217', 'hsa:219', 'hsa:223', 'hsa:224', 'hsa:501']
['hsa:218', 'hsa:221', 'hsa:222']
['hsa:10327']
['hsa:124', 'hsa:125', 'hsa:126', 'hsa:127', 'hsa:128', 'hsa:130', 'hsa:131']
['hsa:5160', 'hsa:5161', 'hsa:5162']
['hsa:5160', 'hsa:5161', 'hsa:5162']
['hsa:1737']
['hsa:160287', 'hsa:3939', 'hsa:3945', 'hsa:3948', 'hsa:92483']
['hsa:5313', 'hsa:5315']
['hsa:2023', 'hsa:2026', 'hsa:2027', 'hsa:387712']
['hsa:441531', 'hsa:5223', 'hsa:5224', 'hsa:669']
['hsa:2597', 'hsa:26330']
['hsa:7167']
['hsa:5211', 'hsa:5213', 'hsa:5214']
['hsa:2203', 'hsa:8789']
['hsa:2821']
['hsa:5236', 'hsa:55276']
['hsa:3098', 'hsa:3099', 'hsa:3101', 'hsa:80201']
['hsa:2645']
['hsa:2821']
['hsa:130589']
['hsa:2645']
['hsa:3098', 'hsa:3099', 'hsa:3101', 'hsa:80201']
['hsa:2538', 'hsa:57818', 'hsa:92579']
['hsa:1738']
['hsa:5230', 'hsa:5232']
['hsa:5105', 'hsa:5106']
['hsa:669']
['hsa:669']
['hsa:55902', 'hsa:84532']
['hsa:83440']
['hsa:83440']
['hsa:9562']